### ISSUE TITLE
[Bug]: My Android TV gets switched off 

### ISSUE THREAD

**Issue by eee-dayal** [siddharthsky/CustTermux-JioTVGo#36]
### Problem description

[Bug]: My Android TV gets switched off as soon as I try coming out of web tv

### What steps will reproduce the bug?

When I press back button to come out of jiotv go app

### System information

```shell
Android TV OS version 11
```

**Comment by Shubham8050** [comment]
I am also facing this issue in fire tv

**Comment by TecnikOfficial** [comment]
can this app reset all other app data ? surprisingly it was working fine but when i restart stb all app data lost i need to reapply settings in my apps again

**Comment by siddharthsky** [comment]
> ### Problem description
> [Bug]: My Android TV gets switched off as soon as I try coming out of web tv
> 
> ### What steps will reproduce the bug?
> When I press back button to come out of jiotv go app
> 
> ### What is the expected behavior?
> _No response_
> 
> ### System information
> ```shell
> Android TV OS version 11
> ```

Note: The app doesn't have permission to turn off your TV. To ensure proper functionality, please make sure you've installed the original APK from the GitHub release and selected the correct architectural APK for your device.

**Comment by TecnikOfficial** [comment]
the app clear data ws due to custermux package installer ... like after installing custermux new option appear along with package installer when i m tryin to sideload apk .... so my stb wasnt able to update apps in background so it automatically reset app data to fix that issue 
for me quick fix was : i set inbuilt package installer to always ( default ) and now its fixed

Additional notes : package installer in custermux can be removed if not needed as u removed dependency 
thanks for this awesome project this simplify things for me 💖

**Comment by siddharthsky** [comment]
> the app clear data ws due to custermux package installer ... like after installing custermux new option appear along with package installer when i m tryin to sideload apk .... so my stb wasnt able to update apps in background so it automatically reset app data to fix that issue for me quick fix was : i set inbuilt package installer to always ( default ) and now its fixed
> 
> Additional notes : package installer in custermux can be removed if not needed as u removed dependency thanks for this awesome project this simplify things for me 💖

I'll remove the package installer in a future update to prevent conflicts; thanks for the feedback
